apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cyclonus
spec:
  version: {{ .TagName }}
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/mattfenwick/kubectl-cyclonus/releases/download/{{ .TagName }}/kubectl-cyclonus_darwin_amd64.tar.gz" .TagName }}
    bin: cyclonus
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/mattfenwick/kubectl-cyclonus/releases/download/{{ .TagName }}/kubectl-cylonus_linux_amd64.tar.gz" .TagName }}
    bin: cyclonus
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/mattfenwick/kubectl-cyclonus/releases/download/{{ .TagName }}/kubectl-cylonus_windows_amd64.tar.gz" .TagName }}
    bin: "cyclonus.exe"
  shortDescription: NetworkPolicy analysis tool suite
  homepage: https://github.com/mattfenwick/kubectl-cyclonus
  description: |
    This plugin provides a suite of tools for working with network policies, including:
    - linting to detect common problems
    - target- and pod-based resolution of policies, to understand how policies work in practice
      and override each other
    - simulation of traffic allow/deny based on application of policies to source and destination
      pod and namespace labels and IP addresses
