apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cyclonus
spec:
  version: "v0.0.2"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/mattfenwick/kubectl-cyclonus/releases/download/v0.0.2/kubectl-cyclonus_linux_amd64.tar.gz
    sha256: "743161ed2dde4a56ddab20a5eef7a944a5cb18e0fdf92a24cc44dd9f68a89eb0"
    files:
    - from: "./kubectl-cyclonus"
      to: "cyclonus"
    - from: LICENSE
      to: "."
    bin: "cyclonus"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/mattfenwick/kubectl-cyclonus/releases/download/v0.0.2/kubectl-cyclonus_darwin_amd64.tar.gz
    sha256: "1252258113e66b52969b25b8949faa10a4a4b3036ca25e8c4b4e9594e47a6aa0"
    files:
    - from: "./kubectl-cyclonus"
      to: "cyclonus"
    - from: LICENSE
      to: "."
    bin: "cyclonus"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/mattfenwick/kubectl-cyclonus/releases/download/v0.0.2/kubectl-cyclonus_windows_amd64.zip
    sha256: "24d9f7e6c2df41417cc1ce93972c78acea0ea1a431dfb199496b445d8c0e6e15"
    files:
    - from: "/kubectl-cyclonus.exe"
      to: "cyclonus.exe"
    - from: LICENSE
      to: "."
    bin: "cyclonus.exe"
  shortDescription: NetworkPolicy analysis tool suite
  homepage: https://github.com/mattfenwick/kubectl-cyclonus
  description: |
    This plugin provides a suite of tools for working with network policies, including:
    - linting to detect common problems
    - target- and pod-based resolution of policies, to understand how policies work in practice
      and override each other
    - simulation of traffic allow/deny based on application of policies to source and destination
      pod and namespace labels and IP addresses

